trigger:
  branches:
    include:
      - main

# Link to your secret and standard variables
variables:
- group: llm-deploy-vars
- name: azureSubscription
  value: 'Pay-As-You-Go'
- name: resourceGroup
  value: 'mlops'
- name: workspaceName
  value: 'llm_mlops'
- name: endpointName
  value: 'stability-endpoint'

stages:
- stage: Deploy
  jobs:
  - job: DeployModel
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'

    - script: |
        # Login using Service Principal
        az login --service-principal -u $SERVICEPRINCIPALID -p $SERVICEPRINCIPALKEY --tenant $TENANTID
        
        # Allow dynamic installation of preview extensions
        az config set extension.dynamic_install_allow_preview=true
        
        # Set the Azure subscription
        az account set --subscription "$AZURESUBSCRIPTION"
        
        # Deploy the model to Azure ML
        az ml online-endpoint create --file endpoint.yml \
          --workspace-name $WORKSPACENAME --resource-group $RESOURCEGROUP
      displayName: 'Deploy Model to Azure ML'

    - script: |
        # Test LLM Endpoint
        az ml online-endpoint invoke \
          --name $ENDPOINTNAME \
          --request-file request.json \
          --workspace-name $WORKSPACENAME \
          --resource-group $RESOURCEGROUP
      displayName: 'Test LLM Endpoint'
