trigger:
  branches:
    include:
      - main
variables:
- group: llm-deploy-vars
- name: azureSubscription
  value: 'test'
- name: resourceGroup
  value: 'mlops'
- name: workspaceName
  value: 'llm_mlop'
- name: endpointName
  value: 'stability-endpoint'
- name: deploymentName
  value: 'stability-deployment'

stages:
- stage: Deploy
  jobs:
  - job: DeployModel
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        
      - script: |
          python -m pip install --upgrade pip
          pip install azure-ai-ml azure-identity
        displayName: 'Install Azure ML SDK'
      
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureSubscription)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            # Debugging: List available subscriptions
            echo "Listing available subscriptions..."
            az account list --output table
            
            # Current subscription
            echo "Current subscription:"
            az account show
            
            # Allow dynamic installation of preview extensions
            echo "Allowing dynamic installation of preview extensions..."
            az config set extension.dynamic_install_allow_preview=true
            
            # Remove conflicting extension if present
            echo "Removing conflicting 'azure-cli-ml' extension..."
            az extension remove --name azure-cli-ml || true
            
            # Install Azure ML CLI extension
            echo "Installing Azure ML CLI extension..."
            az extension add --name ml
            
            # Create the Online Endpoint if it doesn't exist
            echo "Creating/checking online endpoint..."
            if ! az ml online-endpoint show --name $(endpointName) --workspace-name $(workspaceName) --resource-group $(resourceGroup); then
              echo "Creating the online endpoint..."
              az ml online-endpoint create --name $(endpointName) --file endpoint.yml --workspace-name $(workspaceName) --resource-group $(resourceGroup)
            else
              echo "Online endpoint already exists."
            fi
            
            # Create or update the deployment
            echo "Creating/updating model deployment..."
            az ml online-deployment create \
              --name $(deploymentName) \
              --endpoint $(endpointName) \
              --file env.yaml \
              --workspace-name $(workspaceName) \
              --resource-group $(resourceGroup) \
              --all-traffic
            
            # Wait for deployment to be ready
            echo "Waiting for deployment to be ready..."
            az ml online-endpoint wait-for-deployment \
              --name $(endpointName) \
              --deployment $(deploymentName) \
              --workspace-name $(workspaceName) \
              --resource-group $(resourceGroup) \
              --show-output true
            
            # Test the LLM endpoint
            echo "Testing the LLM endpoint..."
            az ml online-endpoint invoke \
              --name $(endpointName) \
              --request-file request.json \
              --workspace-name $(workspaceName) \
              --resource-group $(resourceGroup)
        displayName: 'Deploy and Test Model to Azure ML'
